### ISSUE TITLE
too many requests breaking the api

### ISSUE THREAD

**Issue by dgrandall** [byuoitav/av-api#108]
Sending multiple PUT's quickly to the av-api results in too many database connections, and it needs to be restarted in order to send new PUT's.

**Comment by jessemillar** [comment]
Is this just when running locally?

**Comment by dgrandall** [comment]
yeah, just from running locally. Also, upon further testing, I think it is dependent on the number of requests total, not how quickly they are sent. Sending a lot of requests over a long period of time results in the same issue that can be solved by restarting the api.

**Comment by dgrandall** [comment]
It may be possible that the av-api microservice isn't the issue; it might be the configuration-database-microservice.

**Comment by jessemillar** [comment]
I'd wager that it's the database itself. We've gotta look more into how AWS RDS works to make sure we have things set up properly.

**Comment by xuther** [comment]
I spent some time looking into this - we weren't being strict about calling `defer rows.close()`. We had thought that since the database object is shared across the `accessors` package there was only one connection, but it appears as though each call to `database.query()` opens a new connection. So 65 calls using one query to the database leaves 65 connections open if we don't call `rows.close()`.

I've gone through and fixed a bunch on [this branch](https://github.com/byuoitav/configuration-database-microservice/tree/hotfix/close-databae-connections) - I'm testing now to see if I've gotten most of them. If someone could cast another eye on this to see if I've missed any that would be great!

**Comment by xuther** [comment]
I think I've gotten all of them. If someone could look over [this](https://github.com/byuoitav/configuration-database-microservice/pull/30) pull request to validate that, it would be wonderful.

**Comment by jessemillar** [comment]
Approved and merged.
