### ISSUE TITLE
Errors when combining

### ISSUE THREAD

**Issue by danclegg** [byuoitav/av-api#327]
We have had 2 systems in the last 2 days with these errors instigating help requests:

> Incorrect response for command. (Response: 8\u003e8)

**Comment by danclegg** [comment]
https://byu-oit.slack.com/archives/C6Y44RVH7/p1506610631000171
https://byu-oit.slack.com/archives/C6Y44RVH7/p1506544462000299

**Comment by dannyrandall** [comment]
The Unicode character '\uoo3e' is >. We get these responses from the Kramer when routing video or getting input status. Essentially, this response is saying that input 8 is being routed to output 8 (8>8). The issue we run into with our current Kramer chassis, that will hopefully be fixed with the new one, is that sometimes the Kramer throws in an extra response, so the microservice thinks it's getting the wrong response for the command it just issued. I don't think it's worth putting too much time into now as we are going to replace the chassis in the coming week. If we are still seeing the same issue after replacing the Kramer, we will find a way to deal with the issue.

**Comment by xuther** [comment]
I'm gonna close this issue as we're pulling the kramer's out.
